<a href="https://colab.research.google.com/github/lyntos/Python-MS/blob/main/03_Coding_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



Week 3 Coding Exercises

Complete the following exercises from the textbook (Intro To Python) in a
Juypter Notebook using Google Colab:
7.1 – 7.23



In [ ]:
import numpy as np

In [ ]:
"""
7.1 (Filling arrays) Fill a 2-by-3 array with ones, a 3-by-3 array
with zeros and a 2-by-5 array with 7s.
"""
array_2x3 = np.ones((2, 3))
print(array_2x3)

array_3x3 = np.zeros((3, 3), dtype=int)
print(array_3x3)

array_2x5 = np.full((2, 5), 7)
print(array_2x5)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
"""
7.2 (Broadcasting) Use arange to create a 2-by-2 array containing the
numbers 0–3. Use broadcasting to perform each of the following
operations on the original array:
1. Cube every element of the array.
2. Add 7 to every element of the array.
3. Multiply every element of the array by 2.
"""

# Use arange to create a 2-by-2 array containing the numbers 0–3
arange_array = np.arange(4)
print(arange_array)
arange_array_reshaped = arange_array.reshape(2,2)
print(arange_array_reshaped)

# Cube every element of the array
cubed_arange_array = arange_array_reshaped ** 3

# Add 7 to every element of the array
add_seven_arange_array = arange_array_reshaped + 7

# Multiply every element of the array by 2
multiple_two_arange_array = arange_array_reshaped * 2

print(cubed_arange_array)
print(add_seven_arange_array)
print(multiple_two_arange_array)

[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


In [ ]:
"""7.3 (Element-Wise array Multiplication) Create a 3-by-3 array
containing the even integers from 2 through 18. Create a second 3-by-3
array containing the integers from 9 down to 1, then multiply the first
array by the second."""

# Create a 3-by-3 array containing the even integers from 2 through 18
even_array = np.arange(2, 19, 2).reshape(3, 3)
print(even_array)

# Create a 3-by-3 array containing the integers from 9 down to 1
odd_array = np.arange(9, 0, -1).reshape(3, 3)
print(odd_array)

# multiply the first array by the second
multiplied_array = even_array * odd_array
print(multiplied_array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[18 32 42]
 [48 50 48]
 [42 32 18]]


In [ ]:
"""7.4 (array from List of Lists) Create a 2-by-5 array from an argument
which is a list of the two five-element lists [2, 3, 5, 7, 11] and [13,
17, 19, 23, 29]."""
list_of_lists = [[2, 3, 5, 7, 11], [13, 17, 19, 23, 29]]

array_2x5 = np.asarray(list_of_lists)
print(array_2x5)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


In [ ]:
"""7.5 (Flattening arrays with flatten vs. ravel) Create a 2-by-3
array containing the first six powers of 2 beginning with 2 . Flatten the
array first with method flatten, then with ravel. In each case,
display the result then display the original array to show that it was
unmodified."""

# Create a 2-by-3 array containing the first six powers of 2 beginning with 2
exponents = np.arange(1, 7)
array_powers_of_2 = np.power(2, exponents).reshape(2, 3)
print(array_powers_of_2)

# Flatten the array with method flatten
flattened_array = array_powers_of_2.flatten()
print(flattened_array)
print(array_powers_of_2)

# Flatten the array with method ravel
raveled_array = array_powers_of_2.ravel()
print(raveled_array)
print(array_powers_of_2)

[[ 2  4  8]
 [16 32 64]]
[ 2  4  8 16 32 64]
[[ 2  4  8]
 [16 32 64]]


In [ ]:
"""7.6 (Research: array Method astype) Research in the NumPy
documentation the array method astype, which converts an array’s
elements to another type. Use linspace and reshape to create a 2-by-
3 array with the values 1.1, 2.2, …, 6.6. Then use astype to convert
the array to an array of integers."""

# Use linspace and reshape to create a 2-by- 3 array with the values 1.1, 2.2, …, 6.6
array_1d = np.linspace(1.1, 6.6, 6)
print(array_1d)

array_2d = array_1d.reshape(2, 3)
print(array_2d)

# Use astype to convert the array to an array of integers
array_int = array_2d.astype(int)
print(array_int)

[1.1 2.2 3.3 4.4 5.5 6.6]
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
"""7.7 (Challenge Project: Reimplement NumPy array Output) You saw
that NumPy outputs two-dimensional arrays in a nice column-based
format that right-aligns every element in a field width. The field width’s
size is determined by the array element value that requires the most
character positions to display. To understand how powerful it is to have
this formatting simply built-in, write a function that reimplements
NumPy’s array formatting for two-dimensional arrays using loops.
Assume the array contains only positive integer values."""

"""
Description:
The function displays a two-dimensional list of positive integers in a
column-based format similar to NumPy's array output.

Input:
- A two-dimensional list containing only positive integers.

Output:
- The formatted array displayed with right-aligned columns.
"""

def print_2d_array(array):
  max_width = 0
  for row in array:
    for value in row:
      width = len(str(value))
      if width > max_width:
        max_width = width

  for row in array:
    for value in row:
      print(f"{value:>{max_width}}", end=" ")
    print()

#
data = [[1, 20, 300],[4000, 50, 6],[7, 800, 90,]]
print_2d_array(data)

   1   20  300 
4000   50    6 
   7  800   90 


In [ ]:
"""7.8 (Challenge Project: Reimplement DataFrame Output) You saw that
pandas displays DataFrames in an attractive column-based format with
row and column labels. The values within each column are right aligned in
the same field width, which is determined by that column’s widest value.
To understand how powerful it is to have this formatting built-in, write a
function that reimplements DataFrame formatting using loops. Assume
the DataFrame contains only positive integer values and that both the
row and column labels are each integer values beginning at 0."""

"""
Description:
This function displays a two-dimensional list of positive integers in a
DataFrame-like format similar to pandas. The output includes row and
column labels, and each column is right-aligned using a field width
determined by the widest value in that column.

Input:
- A two-dimensional list (rows x columns) containing positive integers.

Output:
- A formatted table with row and column labels and aligned columns.
"""

def print_dataframe(data):
  rows = len(data)
  cols = len(data[0]) # assuming all lists have same length

  # determine width of row labels
  row_label_width = len(str(rows - 1))

  # determine width for each column
  col_widths = []
  for col in range(cols):
    max_width = len(str(col))  # include column label width
    for row in range(rows):
      value_width = len(str(data[row][col]))
      if value_width > max_width:
        max_width = value_width
    col_widths.append(max_width)

  # print column headers
  print(' ' * (row_label_width + 2), end='')
  for col in range(cols):
    print(f"{col:>{col_widths[col]}} ", end='')
  print()

  # print rows with row labels
  for row in range(rows):
    print(f"{row:>{row_label_width}}  ", end='')
    for col in range(cols):
      print(f"{data[row][col]:>{col_widths[col]}} ", end='')
    print()

data = [
  [1, 20, 300],
  [4000, 50, 6],
  [7, 800, 90]
]

print_dataframe(data)

      0   1   2 
0     1  20 300 
1  4000  50   6 
2     7 800  90 


In [ ]:
"""7.9 (Indexing and Slicing arrays) Create an array containing the
values 1–15, reshape it into a 3-by-5 array, then use indexing and
slicing techniques to perform each of the following operations:
1. Select row 2.
2. Select column 5.
3. Select rows 0 and 1.
4. Select columns 2–4.
5. Select the element that is in row 1 and column 4.
6. Select all elements from rows 1 and 2 that are in columns 0, 2
and 4."""

import numpy as np

# create array 1–15 and reshape to 3-by-5
array = np.arange(1, 16).reshape(3, 5)

print("Original array:")
print(array)

# 1. Select row 2.
print("\n1. Row 2:", array[2])

# 2. Select column 5.
print("\n2. Column 5:", array[:, 4])

# 3. Select rows 0 and 1.
print("\n3. Rows 0 and 1:", array[0:2])

# 4. Select columns 2–4.
print("\n4. Columns 2–4:", array[:, 2:5])

# 5. Select the element that is in row 1 and column 4.
print("\n5. Element in row 1 and column 4:", array[1, 4])

# 6. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4
print("\n6. All elements from rows 1 and 2 and in columns 0, 2 and 4:")
print(array[1:3, [0, 2, 4]])

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

1. Row 2: [11 12 13 14 15]

2. Column 5: [ 5 10 15]

3. Rows 0 and 1: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

4. Columns 2–4: [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]

5. Element in row 1 and column 4: 10

6. All elements from rows 1 and 2 and in columns 0, 2 and 4:
[[ 6  8 10]
 [11 13 15]]


In [ ]:
"""7.10 (Project: Two-Player, Two-Dimensional Tic-Tac-Toe) Write a script
to play two-dimensional Tic-Tac-Toe between two human players who
alternate entering their moves on the same computer. Use a 3-by-3 twodimensional
array. Each player indicates their moves by entering a pair
of numbers representing the row and column indices of the square in
which they want to place their mark, either an 'X' or an 'O'. When the
first player moves, place an 'X' in the specified square. When the second
player moves, place an 'O' in the specified square. Each move must be to
an empty square. After each move, determine whether the game has been
won and whether it’s a draw."""

"""
Description:
This script plays two-player Tic-Tac-Toe on a 3-by-3 two-dimensional array.
Two human players alternate turns on the same computer. Player 1 places
'X' and Player 2 places 'O'. Each move is entered as a pair of integers
(row and column indices). Moves must be made to an empty square.
After each move, the script determines whether the game has been won
or whether the game is a draw.

Input:
- Row and column indices (0–2) entered by the players.

Output:
- The board after each move.
- A message indicating a win or a draw.
"""

import numpy as np


def display_board(board):
  print()
  for row in range(3):
    print(" ", end="")
    for col in range(3):
      print(board[row, col], end="")
      if col < 2:
        print(" | ", end="")
    print()
    if row < 2:
      print("---+---+---")
  print()


def is_winner(board, mark):
  # check rows and columns
  for i in range(3):
    if np.all(board[i, :] == mark):
      return True
    if np.all(board[:, i] == mark):
      return True

  # check diagonals
  if np.all(np.diag(board) == mark):
    return True
  if np.all(np.diag(np.fliplr(board)) == mark):
    return True

  return False


def is_draw(board):
  return not np.any(board == ' ')


board = np.full((3, 3), ' ', dtype='<U1')

current_player = 1
current_mark = 'X'

print("Two-Player Tic-Tac-Toe")
print("Enter moves as row and column indices from 0 to 2.")
display_board(board)

while True:
  move = input(f"Player {current_player} ({current_mark}) enter row,col: ").strip()

  # basic input validation
  if ',' not in move:
    print("Invalid format. Enter as row,col (example: 1,2).")
    continue

  parts = move.split(',')
  if len(parts) != 2:
    print("Invalid format. Enter as row,col (example: 1,2).")
    continue

  if not parts[0].strip().isdigit() or not parts[1].strip().isdigit():
    print("Row and column must be integers from 0 to 2.")
    continue

  row = int(parts[0].strip())
  col = int(parts[1].strip())

  if row < 0 or row > 2 or col < 0 or col > 2:
    print("Row and column must be in the range 0 to 2.")
    continue

  if board[row, col] != ' ':
    print("That square is not empty. Try again.")
    continue

  # place the mark
  board[row, col] = current_mark
  display_board(board)

  # check win
  if is_winner(board, current_mark):
    print(f"Player {current_player} wins!")
    break

  # check draw
  if is_draw(board):
    print("It's a draw!")
    break

  # switch players
  if current_player == 1:
    current_player = 2
    current_mark = 'O'
  else:
    current_player = 1
    current_mark = 'X'

Two-Player Tic-Tac-Toe
Enter moves as row and column indices from 0 to 2.

   |   |  
---+---+---
   |   |  
---+---+---
   |   |  

Player 1 (X) enter row,col: 1
Invalid format. Enter as row,col (example: 1,2).
Player 1 (X) enter row,col: 2
Invalid format. Enter as row,col (example: 1,2).
Player 1 (X) enter row,col: 1,3
Row and column must be in the range 0 to 2.
Player 1 (X) enter row,col: 1,2

   |   |  
---+---+---
   |   | X
---+---+---
   |   |  

Player 2 (O) enter row,col: 0,1

   | O |  
---+---+---
   |   | X
---+---+---
   |   |  

Player 1 (X) enter row,col: 1,1

   | O |  
---+---+---
   | X | X
---+---+---
   |   |  

Player 2 (O) enter row,col: 0,0

 O | O |  
---+---+---
   | X | X
---+---+---
   |   |  

Player 1 (X) enter row,col: 0,3
Row and column must be in the range 0 to 2.
Player 1 (X) enter row,col: 0,2

 O | O | X
---+---+---
   | X | X
---+---+---
   |   |  

Player 2 (O) enter row,col: 2,2

 O | O | X
---+---+---
   | X | X
---+---+---
   |   | O

Player 1 (X

In [ ]:
"""7.11 (Challenge Project: Tic-Tac-Toe with Player Against the Computer)
Modify your script from the previous exercise so that the computer makes
the moves for one of the players. Also, allow the player to specify whether
he or she wants to go first or second."""

"""
Description:
This script plays two-dimensional Tic-Tac-Toe between a human player and
the computer. The player can choose whether to go first or second.
The game uses a 3-by-3 two-dimensional array. The human player uses 'X'
and the computer uses 'O'. After each move, the script checks for a win
or a draw.

Input:
- Player choice to go first or second.
- Row and column indices for the player's moves.

Output:
- The game board after each move.
- A message indicating whether the player wins, the computer wins, or
  the game ends in a draw.
"""

import numpy as np
import random


def display_board(board):
  print()
  for row in range(3):
    print(" ", end="")
    for col in range(3):
      print(board[row, col], end="")
      if col < 2:
        print(" | ", end="")
    print()
    if row < 2:
      print("---+---+---")
  print()


def is_winner(board, mark):
  for i in range(3):
    if np.all(board[i, :] == mark):
      return True
    if np.all(board[:, i] == mark):
      return True

  if np.all(np.diag(board) == mark):
    return True
  if np.all(np.diag(np.fliplr(board)) == mark):
    return True

  return False


def is_draw(board):
  return not np.any(board == ' ')


def computer_move(board):
  empty_squares = []

  for row in range(3):
    for col in range(3):
      if board[row, col] == ' ':
        empty_squares.append((row, col))

  return random.choice(empty_squares)


# initialize board
board = np.full((3, 3), ' ', dtype='<U1')

print("Tic-Tac-Toe: Player vs Computer")
choice = input("Do you want to go first or second? (1 or 2): ").strip()

if choice == '1':
  player_mark = 'X'
  computer_mark = 'O'
  player_turn = True
else:
  player_mark = 'O'
  computer_mark = 'X'
  player_turn = False

display_board(board)

while True:
  if player_turn:
    move = input("Enter your move as row,col (0–2): ").strip()

    if ',' not in move:
      print("Invalid format. Use row,col.")
      continue

    parts = move.split(',')
    if not parts[0].isdigit() or not parts[1].isdigit():
      print("Row and column must be integers from 0 to 2.")
      continue

    row = int(parts[0])
    col = int(parts[1])

    if row not in range(3) or col not in range(3):
      print("Row and column must be in the range 0 to 2.")
      continue

    if board[row, col] != ' ':
      print("That square is not empty.")
      continue

    board[row, col] = player_mark
    display_board(board)

    if is_winner(board, player_mark):
      print("You win!")
      break

  else:
    row, col = computer_move(board)
    board[row, col] = computer_mark
    print(f"Computer moves to {row},{col}")
    display_board(board)

    if is_winner(board, computer_mark):
      print("Computer wins!")
      break

  if is_draw(board):
    print("It's a draw!")
    break

  player_turn = not player_turn

Tic-Tac-Toe: Player vs Computer
Do you want to go first or second? (1 or 2): 0,2

   |   |  
---+---+---
   |   |  
---+---+---
   |   |  

Computer moves to 1,1

   |   |  
---+---+---
   | X |  
---+---+---
   |   |  

Enter your move as row,col (0–2): 0,2

   |   | O
---+---+---
   | X |  
---+---+---
   |   |  

Computer moves to 2,2

   |   | O
---+---+---
   | X |  
---+---+---
   |   | X

Enter your move as row,col (0–2): 0,0

 O |   | O
---+---+---
   | X |  
---+---+---
   |   | X

Computer moves to 1,2

 O |   | O
---+---+---
   | X | X
---+---+---
   |   | X

Enter your move as row,col (0–2): 1,0

 O |   | O
---+---+---
 O | X | X
---+---+---
   |   | X

Computer moves to 2,1

 O |   | O
---+---+---
 O | X | X
---+---+---
   | X | X

Enter your move as row,col (0–2): 2,0

 O |   | O
---+---+---
 O | X | X
---+---+---
 O | X | X

You win!


In [ ]:
"""7.12 (Super Challenge Project: 3D Tic-Tac-Toe with Player Against the
Computer) Develop a script that plays three-dimensional Tic-Tac-Toe on a
4-by-4-by-4 board. [Note: This is an extremely challenging project! In the
“Deep Learning” chapter, you’ll learn techniques that will help you
develop and AI-based approach to solving this problem.]"""

"""
Description:
This script plays 3D Tic-Tac-Toe on a 4-by-4-by-4 board between a human
player and the computer. The player chooses whether to go first or second.
Moves are entered as three integers: layer, row, and column (0–3).
The game checks for a winner after each move by evaluating all possible
4-in-a-row winning lines in the 4x4x4 cube. The computer uses a simple
strategy:
1) If it can win in one move, it plays that move.
2) Else, if it must block the player from winning in one move, it blocks.
3) Else, it chooses a random available square.

Input:
- Player choice to go first or second (1 or 2).
- Player moves as "layer,row,col" values from 0 to 3.

Output:
- The 3D board displayed layer by layer after each move.
- Win/draw messages at the end.
"""

import numpy as np
import random


def generate_winning_lines(size=4):
  lines = []

  # rows in each layer
  for z in range(size):
    for y in range(size):
      line = []
      for x in range(size):
        line.append((z, y, x))
      lines.append(line)

  # columns in each layer
  for z in range(size):
    for x in range(size):
      line = []
      for y in range(size):
        line.append((z, y, x))
      lines.append(line)

  # verticals through layers
  for y in range(size):
    for x in range(size):
      line = []
      for z in range(size):
        line.append((z, y, x))
      lines.append(line)

  # diagonals within each layer (2 per layer)
  for z in range(size):
    diag1 = []
    diag2 = []
    for i in range(size):
      diag1.append((z, i, i))
      diag2.append((z, i, size - 1 - i))
    lines.append(diag1)
    lines.append(diag2)

  # diagonals across layers for each row (y fixed)
  for y in range(size):
    diag1 = []
    diag2 = []
    for i in range(size):
      diag1.append((i, y, i))
      diag2.append((i, y, size - 1 - i))
    lines.append(diag1)
    lines.append(diag2)

  # diagonals across layers for each column (x fixed)
  for x in range(size):
    diag1 = []
    diag2 = []
    for i in range(size):
      diag1.append((i, i, x))
      diag2.append((i, size - 1 - i, x))
    lines.append(diag1)
    lines.append(diag2)

  # 4 main space diagonals through the cube
  diag1 = []
  diag2 = []
  diag3 = []
  diag4 = []
  for i in range(size):
    diag1.append((i, i, i))
    diag2.append((i, i, size - 1 - i))
    diag3.append((i, size - 1 - i, i))
    diag4.append((i, size - 1 - i, size - 1 - i))
  lines.append(diag1)
  lines.append(diag2)
  lines.append(diag3)
  lines.append(diag4)

  return lines


def display_board(board):
  print()
  for z in range(4):
    print(f"Layer {z}:")
    for y in range(4):
      print(" ", end="")
      for x in range(4):
        print(board[z, y, x], end="")
        if x < 3:
          print(" | ", end="")
      print()
      if y < 3:
        print("---+---+---+---")
    print()


def is_winner(board, mark, lines):
  for line in lines:
    won = True
    for (z, y, x) in line:
      if board[z, y, x] != mark:
        won = False
        break
    if won:
      return True
  return False


def is_draw(board):
  return not np.any(board == ' ')


def empty_squares(board):
  empties = []
  for z in range(4):
    for y in range(4):
      for x in range(4):
        if board[z, y, x] == ' ':
          empties.append((z, y, x))
  return empties


def find_winning_move(board, mark, lines):
  for (z, y, x) in empty_squares(board):
    board[z, y, x] = mark
    if is_winner(board, mark, lines):
      board[z, y, x] = ' '
      return (z, y, x)
    board[z, y, x] = ' '
  return None


def computer_move(board, computer_mark, player_mark, lines):
  # 1) win if possible
  move = find_winning_move(board, computer_mark, lines)
  if move is not None:
    return move

  # 2) block player if needed
  move = find_winning_move(board, player_mark, lines)
  if move is not None:
    return move

  # 3) otherwise choose a random empty square
  return random.choice(empty_squares(board))


lines = generate_winning_lines(4)
board = np.full((4, 4, 4), ' ', dtype='<U1')

print("3D Tic-Tac-Toe (4x4x4): Player vs Computer")
print("Enter moves as layer,row,col using values 0–3.")
choice = input("Do you want to go first or second? (1 or 2): ").strip()

if choice == '1':
  player_mark = 'X'
  computer_mark = 'O'
  player_turn = True
else:
  player_mark = 'O'
  computer_mark = 'X'
  player_turn = False

display_board(board)

while True:
  if player_turn:
    move = input("Enter your move as layer,row,col (0–3): ").strip()

    if ',' not in move:
      print("Invalid format. Use layer,row,col (example: 0,2,3).")
      continue

    parts = move.split(',')
    if len(parts) != 3:
      print("Invalid format. Use layer,row,col (example: 0,2,3).")
      continue

    if not parts[0].strip().isdigit() or not parts[1].strip().isdigit() or not parts[2].strip().isdigit():
      print("Layer, row, and column must be integers from 0 to 3.")
      continue

    z = int(parts[0].strip())
    y = int(parts[1].strip())
    x = int(parts[2].strip())

    if z not in range(4) or y not in range(4) or x not in range(4):
      print("Layer, row, and column must be in the range 0 to 3.")
      continue

    if board[z, y, x] != ' ':
      print("That square is not empty. Try again.")
      continue

    board[z, y, x] = player_mark
    display_board(board)

    if is_winner(board, player_mark, lines):
      print("You win!")
      break

  else:
    z, y, x = computer_move(board, computer_mark, player_mark, lines)
    board[z, y, x] = computer_mark
    print(f"Computer moves to {z},{y},{x}")
    display_board(board)

    if is_winner(board, computer_mark, lines):
      print("Computer wins!")
      break

  if is_draw(board):
    print("It's a draw!")
    break

  player_turn = not player_turn


3D Tic-Tac-Toe (4x4x4): Player vs Computer
Enter moves as layer,row,col using values 0–3.
Do you want to go first or second? (1 or 2): 2

Layer 0:
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  

Layer 1:
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  

Layer 2:
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  

Layer 3:
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  

Computer moves to 0,3,1

Layer 0:
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   | X |   |  

Layer 1:
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  

Layer 2:
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  
---+---+---+---
   |   |   |  

Layer 3:
  

KeyboardInterrupt: Interrupted by user

In [ ]:
"""7.13 (Research and Use Other Broadcasting Capabilities) Research the
NumPy broadcasting rules, then create your own arrays to test the rules."""

"""
Numpy Broadcasting rules

When NumPy combines arrays element-by-element (e.g., +, -, *, /),
it compares shapes from the last dimension moving left:
	1.	If the number of dimensions differs, pad the smaller shape with
      1s on the left.  
	2.	Two dimensions are compatible if they are equal, or one of them
      is 1 (the 1 “stretches”).  
	3.	If any dimension pair is not equal and neither is 1, broadcasting
      fails with a ValueError.  
"""

"""
Description:
Tests NumPy broadcasting rules by creating arrays with different shapes,
performing operations, and printing the resulting shapes/values.
"""

import numpy as np

# 1) Scalar broadcasts to any shape
a = np.array([1, 2, 3])
print("1) scalar + vector")
print("a.shape:", a.shape)
print("(a + 10):", a + 10)
print()

# 2) (3, 1) + (1, 4) -> (3, 4)  (classic broadcast grid)
b = np.array([[1], [2], [3]])        # shape (3, 1)
c = np.array([[10, 20, 30, 40]])     # shape (1, 4)
print("2) (3,1) + (1,4) -> (3,4)")
print("b.shape:", b.shape, "c.shape:", c.shape)
print("result:\n", b + c)
print("result.shape:", (b + c).shape)
print()

# 3) (2, 3) + (3,) -> (2, 3)  (1D treated like (1,3))
d = np.array([[1, 2, 3],
              [4, 5, 6]])            # shape (2, 3)
e = np.array([10, 20, 30])           # shape (3,)
print("3) (2,3) + (3,) -> (2,3)")
print("d.shape:", d.shape, "e.shape:", e.shape)
print("result:\n", d + e)
print()

# 4) Broadcasting failure example: (2, 3) and (2, 2) are incompatible
f = np.ones((2, 3), dtype=int)
g = np.ones((2, 2), dtype=int)
print("4) incompatible shapes (2,3) and (2,2)")
print("f.shape:", f.shape, "g.shape:", g.shape)
try:
  print(f + g)
except ValueError as error:
  print("Broadcasting error:", error)
print()

# 5) 3D + 2D: (2,3,4) + (3,4) -> (2,3,4)  (2D treated like (1,3,4))
h = np.arange(24).reshape(2, 3, 4)
i = np.ones((3, 4), dtype=int)
print("5) (2,3,4) + (3,4) -> (2,3,4)")
print("h.shape:", h.shape, "i.shape:", i.shape)
result = h + i
print("result.shape:", result.shape)
print("result[0]:\n", result[0])

1) scalar + vector
a.shape: (3,)
(a + 10): [11 12 13]

2) (3,1) + (1,4) -> (3,4)
b.shape: (3, 1) c.shape: (1, 4)
result:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
result.shape: (3, 4)

3) (2,3) + (3,) -> (2,3)
d.shape: (2, 3) e.shape: (3,)
result:
 [[11 22 33]
 [14 25 36]]

4) incompatible shapes (2,3) and (2,2)
f.shape: (2, 3) g.shape: (2, 2)
Broadcasting error: operands could not be broadcast together with shapes (2,3) (2,2) 

5) (2,3,4) + (3,4) -> (2,3,4)
h.shape: (2, 3, 4) i.shape: (3, 4)
result.shape: (2, 3, 4)
result[0]:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
"""7.14 (Horizontal and Vertical Stacking) Create the two-dimensional
arrays
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

1. Use vertical stacking to create the 4-by-2 array named
array3 with array1 stacked on top of array2.
2. Use horizontal stacking to create the 2-by-4 array named
array4 with array2 to the right of array1.
3. Use vertical stacking with two copies of array4 to create a 4-
by-4 array5.
4. Use horizontal stacking with two copies of array3 to create a
4-by-4 array6."""

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# 1. 4-by-2 vertical stacked array
array3 = np.vstack((array1, array2))
print("Array 3:")
print(array3)

# 2. 2-by-4 horizontal stack
array4 = np.hstack((array1, array2))
print("\nArray 4:")
print(array4)

# 3. 4-by-4 vertical stacking with two copies of array4
array5 = np.vstack((array4, array4))
print("\nArray 5:")
print(array5)

# 4. 4-by-4 horizontal stacking with two copies of array3
array6 = np.hstack((array3, array3))
print("\nArray 6:")
print(array6)

Array 3:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Array 4:
[[0 1 4 5]
 [2 3 6 7]]

Array 5:
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

Array 6:
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [ ]:
"""7.15 (Research and Use NumPy’s concatenate Function) Research
NumPy function concatenate, then use it to reimplement the previous
exercise."""

"""
Description:
This script demonstrates NumPy array construction and combination using
the concatenate function. The resulting arrays are then used to test
NumPy broadcasting rules, reimplementing the experiments from Exercise 7.13.
"""

import numpy as np

# -------------------------------------------------
# 1) Build arrays using concatenate (row-wise)
# -------------------------------------------------

row1 = np.array([[1, 2, 3]])
row2 = np.array([[4, 5, 6]])

matrix = np.concatenate((row1, row2), axis=0)

print("Matrix created with concatenate:")
print(matrix)
print("Shape:", matrix.shape)
print()

# -------------------------------------------------
# 2) Broadcasting with 1D array
# -------------------------------------------------

vector = np.array([10, 20, 30])

print("Broadcasting matrix + vector:")
print(matrix + vector)
print()

# -------------------------------------------------
# 3) Build column vector using concatenate
# -------------------------------------------------

col1 = np.array([[1]])
col2 = np.array([[2]])
col3 = np.array([[3]])

column = np.concatenate((col1, col2, col3), axis=0)

print("Column vector created with concatenate:")
print(column)
print("Shape:", column.shape)
print()

# -------------------------------------------------
# 4) Broadcasting (3,1) + (1,4)
# -------------------------------------------------

row = np.array([[10, 20, 30, 40]])

result = column + row

print("Broadcasting (3,1) + (1,4):")
print(result)
print("Result shape:", result.shape)
print()

# -------------------------------------------------
# 5) Demonstrate incompatible shapes
# -------------------------------------------------

a = np.ones((2, 3), dtype=int)
b = np.ones((2, 2), dtype=int)

print("Attempting invalid broadcast:")
try:
  print(a + b)
except ValueError as error:
  print("Broadcasting error:", error)

Matrix created with concatenate:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Broadcasting matrix + vector:
[[11 22 33]
 [14 25 36]]

Column vector created with concatenate:
[[1]
 [2]
 [3]]
Shape: (3, 1)

Broadcasting (3,1) + (1,4):
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
Result shape: (3, 4)

Attempting invalid broadcast:
Broadcasting error: operands could not be broadcast together with shapes (2,3) (2,2) 


In [ ]:
"""7.16 (Research: NumPy tile Function) Research and use NumPy’s
tile function to create a checkerboard pattern of dashes and asterisks."""

"""
Description:
This script uses NumPy's tile function to create a checkerboard pattern
consisting of dashes ('-') and asterisks ('*'). The pattern is created by
repeating a base 2-by-2 array.
"""

import numpy as np

# base 2x2 checkerboard pattern
base_pattern = np.array([
  ['-', '*'],
  ['*', '-']
])

# create an 8x8 checkerboard by tiling the base pattern
checkerboard = np.tile(base_pattern, (4, 4))

print("Checkerboard pattern:")
print(checkerboard)

Checkerboard pattern:
[['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']]


In [ ]:
"""7.17 (Research: NumPy bincount Functions) Research and use the
NumPy bincount function to count the number of occurrences of each
non-negative integer in a 5-by-5 array of random integers in the range
0–99."""

"""
Description:
This script creates a 5-by-5 NumPy array of random integers in the range
0–99, then uses NumPy's bincount function to count the number of
occurrences of each integer in the array.
"""

import numpy as np

# create a 5x5 array of random integers from 0 to 99
array = np.random.randint(0, 100, size=(5, 5))

print("5x5 array:")
print(array)
print()

# flatten the array and count occurrences
counts = np.bincount(array.flatten())

print("Value : Count")
print("--------------")

for value in range(len(counts)):
  if counts[value] > 0:
    print(f"{value:>5} : {counts[value]}")

5x5 array:
[[ 8 94 86  7 12]
 [63 24 97 41 59]
 [ 3 95 30 15 48]
 [26 47 66  1 10]
 [64 89 61 60 90]]

Value : Count
--------------
    1 : 1
    3 : 1
    7 : 1
    8 : 1
   10 : 1
   12 : 1
   15 : 1
   24 : 1
   26 : 1
   30 : 1
   41 : 1
   47 : 1
   48 : 1
   59 : 1
   60 : 1
   61 : 1
   63 : 1
   64 : 1
   66 : 1
   86 : 1
   89 : 1
   90 : 1
   94 : 1
   95 : 1
   97 : 1


In [ ]:
"""7.18 (Median and Mode of an array) NumPy arrays offer a mean
method, but not median or mode. Write functions median and mode
that use existing NumPy capabilities to determine the median (middle) and
mode (most frequent) of the values in an array. Your functions should
determine the median and mode regardless of the array’s shape. Test your
function on three arrays of different shapes."""

import numpy as np


def median(array):
  """
  Returns the median value of the array, regardless of shape.
  """
  flattened = array.flatten()
  sorted_values = np.sort(flattened)
  n = len(sorted_values)

  if n % 2 == 1:
    return sorted_values[n // 2]
  else:
    return (sorted_values[n // 2 - 1] + sorted_values[n // 2]) / 2


def mode(array):
  """
  Returns the mode (most frequent value) of the array.
  """
  flattened = array.flatten()
  counts = np.bincount(flattened)
  return np.argmax(counts)

# Testing on arrays of different shapes

array1 = np.array([1, 2, 2, 3, 4, 5, 2])
array2 = np.array([[5, 1, 3],
                   [2, 2, 4]])
array3 = np.array([[[7, 8], [8, 9]],
                   [[8, 10], [11, 8]]])

arrays = [array1, array2, array3]

for i, arr in enumerate(arrays, start=1):
  print(f"Array {i}:")
  print(arr)
  print("Median:", median(arr))
  print("Mode:", mode(arr))
  print()

Array 1:
[1 2 2 3 4 5 2]
Median: 2
Mode: 2

Array 2:
[[5 1 3]
 [2 2 4]]
Median: 2.5
Mode: 2

Array 3:
[[[ 7  8]
  [ 8  9]]

 [[ 8 10]
  [11  8]]]
Median: 8.0
Mode: 8



In [ ]:
"""7.19 (Enhanced Median and Mode of an array) Modify your functions
from the previous exercise to allow the user to provide an axis keyword
argument so the calculations can be performed row-by-row or column-bycolumn
on a two-dimensional array."""

import numpy as np


def median(array):
  """
  Returns the median value of the array, regardless of shape.
  """
  flattened = array.flatten()
  sorted_values = np.sort(flattened)
  n = len(sorted_values)

  if n % 2 == 1:
    return sorted_values[n // 2]
  else:
    return (sorted_values[n // 2 - 1] + sorted_values[n // 2]) / 2


def mode(array):
  """
  Returns the mode (most frequent value) of the array.
  """
  flattened = array.flatten()
  counts = np.bincount(flattened)
  return np.argmax(counts)

# Testing on arrays of different shapes

array1 = np.array([1, 2, 2, 3, 4, 5, 2])
array2 = np.array([[5, 1, 3],
                   [2, 2, 4]])
array3 = np.array([[[7, 8], [8, 9]],
                   [[8, 10], [11, 8]]])

arrays = [array1, array2, array3]

for i, arr in enumerate(arrays, start=1):
  print(f"Array {i}:")
  print(arr)
  print("Median:", median(arr))
  print("Mode:", mode(arr))
  print()

Array 1:
[1 2 2 3 4 5 2]
Median: 2
Mode: 2

Array 2:
[[5 1 3]
 [2 2 4]]
Median: 2.5
Mode: 2

Array 3:
[[[ 7  8]
  [ 8  9]]

 [[ 8 10]
  [11  8]]]
Median: 8.0
Mode: 8



In [ ]:
"""7.20 (Performance Analysis) In this chapter, we used %timeit to
compare the average execution times of generating a list of 6,000,000
random die rolls vs. generating an array of 6,000,000 random die rolls.
Though we saw approximately two orders of magnitude performance
improvement with array, we generated the list and the array using two
different random-number generators and different techniques for building
each collection. If you use the same techniques we showed to generate a
one-element list and a one-element array, creating the list is slightly faster.
Repeat the %timeit operations for one-element collections. Then do it
again for 10, 100, 1000, 10,000, 100,000, and 1,000,000 elements and
compare the results on your system. The table below shows the results on
our system, with measurements in nanoseconds (ns), microseconds (μs),
milliseconds (ms) and seconds (s).

This analysis shows why %timeit is convenient for quick performance
studies. However, you also need to develop performance-analysis wisdom.
Many factors can affect performance—the underlying hardware, the
operating system, the interpreter or compiler you’re using, the other
applications running on your computer at the same time, and many more.
The way we thought about performance over the years is changing rapidly
now with big data, data analytics and artificial intelligence. As we head
into the AI portion of the book, you’ll place enormous performance
demands on your system, so it’s always good to be thinking about
performance issues.
"""
import random
import numpy as np

# 1 element
%timeit [random.randrange(1, 7)]
%timeit np.random.randint(1, 7, size=1)

# 10 elements
%timeit [random.randrange(1, 7) for _ in range(10)]
%timeit np.random.randint(1, 7, size=10)

# 100 elements
%timeit [random.randrange(1, 7) for _ in range(100)]
%timeit np.random.randint(1, 7, size=100)

# 1000 elements
%timeit [random.randrange(1, 7) for _ in range(1_000)]
%timeit np.random.randint(1, 7, size=1_000)

# 10,000 elements
%timeit [random.randrange(1, 7) for _ in range(10_000)]
%timeit np.random.randint(1, 7, size=10_000)

# 100,000 elements
%timeit [random.randrange(1, 7) for _ in range(100_000)]
%timeit np.random.randint(1, 7, size=100_000)

# 1,000,000 elements
%timeit [random.randrange(1, 7) for _ in range(1_000_000)]
%timeit np.random.randint(1, 7, size=1_000_000)


501 ns ± 6.09 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
9.5 µs ± 1.79 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.46 µs ± 80.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
9.51 µs ± 2.06 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
42.6 µs ± 712 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
10.2 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
446 µs ± 48.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
20.5 µs ± 2.26 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.46 ms ± 513 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
117 µs ± 7.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
57 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.03 ms ± 2.73 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
599 ms ± 160 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
10.2 ms ± 73.5 µs per loop (mean ± std. dev. of 7 run

In [ ]:
"""7.21 (Shallow vs. Deep Copy) In this chapter, we discussed shallow vs.
deep copies of arrays. Python’s built-in list and dictionary types have
copy methods that perform shallow copies. Using the following
dictionary
dictionary = {'Sophia': [97, 88]}
demonstrate that a dictionary’s copy method indeed performs a shallow
copy. To do so, call copy to make the shallow copy, modify the list stored
in the original dictionary, then display both dictionaries to see that they
have the same contents.
Next, use the copy module’s deepcopy function to create a deep copy
of the dictionary. Modify the list stored in the original dictionary, then
display both dictionaries to prove that each has its own data."""

# Shallow copy
# original dictionary
dictionary = {'Sophia': [97, 88]}

# make a shallow copy
shallow_copy = dictionary.copy()

# modify the list in the original dictionary
dictionary['Sophia'].append(100)

print("Original dictionary:")
print(dictionary)

print("\nShallow copy:")
print(shallow_copy)

# Deep copy
import copy

# reset original dictionary
dictionary = {'Sophia': [97, 88]}

# make a deep copy
deep_copy = copy.deepcopy(dictionary)

# modify the list in the original dictionary
dictionary['Sophia'].append(100)

print("Original dictionary:")
print(dictionary)

print("\nDeep copy:")
print(deep_copy)

Original dictionary:
{'Sophia': [97, 88, 100]}

Shallow copy:
{'Sophia': [97, 88, 100]}
Original dictionary:
{'Sophia': [97, 88, 100]}

Deep copy:
{'Sophia': [97, 88]}


In [ ]:
"""7.22 (Pandas: Series) Perform the following tasks with pandas
Series:
1. Create a Series from the list [7, 11, 13, 17].
2. Create a Series with five elements that are all 100.0.
3. Create a Series with 20 elements that are all random numbers
in the range 0 to 100. Use method describe to produce the
Series’ basic descriptive statistics.
4. Create a Series called temperatures of the floating-point
values 98.6, 98.9, 100.2 and 97.9. Using the index
keyword argument, specify the custom indices 'Julie',
'Charlie', 'Sam' and 'Andrea'.
5. Form a dictionary from the names and values in Part (d), then use
it to initialize a Series."""

import pandas as pd
import numpy as np

# 1. Create a Series from the list [7, 11, 13, 17].
series1 = pd.Series([7, 11, 13, 17])
print("Series from list:")
print(series1)
print()

# 2. Create a Series with five elements that are all 100.0.
series2 = pd.Series([100.0] * 5)
print("Series of five 100.0 values:")
print(series2)
print()

# 3. Create a Series with 20 random numbers (0–100) and use describe
series3 = pd.Series(np.random.uniform(0, 100, 20))
print("Random Series (0–100):")
print(series3)
print()

print("Descriptive statistics:")
print(series3.describe())
print()

# 4. Create a Series called temperatures with custom indices
temperatures = pd.Series(
  [98.6, 98.9, 100.2, 97.9],
  index=['Julie', 'Charlie', 'Sam', 'Andrea']
)

print("Temperatures Series with custom indices:")
print(temperatures)
print()

# 5. Create a dictionary from Part (4) and initialize a Series
temp_dict = {
  'Julie': 98.6,
  'Charlie': 98.9,
  'Sam': 100.2,
  'Andrea': 97.9
}

series_from_dict = pd.Series(temp_dict)

print("Series created from dictionary:")
print(series_from_dict)

Series from list:
0     7
1    11
2    13
3    17
dtype: int64

Series of five 100.0 values:
0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64

Random Series (0–100):
0     39.507194
1     66.271280
2      8.238436
3     77.974162
4     62.139017
5     79.013027
6     21.014535
7     44.928102
8     65.748807
9     52.230597
10    97.740165
11    23.637578
12    49.498601
13    33.524668
14    79.443425
15    17.913344
16    54.565201
17     7.927563
18    36.495858
19     0.459560
dtype: float64

Descriptive statistics:
count    20.000000
mean     45.913556
std      27.381567
min       0.459560
25%      22.981817
50%      47.213352
75%      65.879425
max      97.740165
dtype: float64

Temperatures Series with custom indices:
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64

Series created from dictionary:
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64


In [ ]:
"""7.23 (Pandas: DataFrames) Perform the following tasks with pandas
DataFrames:
1. Create a DataFrame named temperatures from a
dictionary of three temperature readings each for 'Maxine',
'James' and 'Amanda'.
2. Recreate the DataFrame temperatures in Part (a) with
custom indices using the index keyword argument and a list
containing 'Morning', 'Afternoon' and 'Evening'.
3. Select from temperatures the column of temperature
readings for 'Maxine'.
4. Select from temperatures the row of 'Morning'
temperature readings.
5. Select from temperatures the rows for 'Morning' and
'Evening' temperature readings.
6. Select from temperatures the columns of temperature
readings for 'Amanda' and 'Maxine'.
7. Select from temperatures the elements for 'Amanda' and
'Maxine' in the 'Morning' and 'Afternoon'.
8. Use the describe method to produce temperatures’
descriptive statistics.
9. Transpose temperatures.
10. Sort temperatures so that its column names are in
alphabetical order.
"""

"""
Description:
This script demonstrates basic pandas DataFrame operations, including
creation from dictionaries, custom indices, row and column selection,
descriptive statistics, transposition, and sorting.
"""

import pandas as pd

# 1. Create a DataFrame named temperatures from a dictionary
temps_dict = {
  'Maxine': [98.6, 99.1, 98.9],
  'James': [97.9, 98.4, 98.0],
  'Amanda': [98.2, 98.8, 98.5]
}

temperatures = pd.DataFrame(temps_dict)
print("1. DataFrame from dictionary:")
print(temperatures)
print()

# 2. Recreate the DataFrame with custom indices
temperatures = pd.DataFrame(
  temps_dict,
  index=['Morning', 'Afternoon', 'Evening']
)

print("2. DataFrame with custom indices:")
print(temperatures)
print()

# 3. Select the column of temperature readings for ‘Maxine’
print("3. Maxine's temperatures:")
print(temperatures['Maxine'])
print()

# 4. Select the row of ‘Morning’ temperature readings
print("4. Morning temperatures:")
print(temperatures.loc['Morning'])
print()

# 5. Select the rows for ‘Morning’ and ‘Evening’
print("5. Morning and Evening temperatures:")
print(temperatures.loc[['Morning', 'Evening']])
print()

# 6. Select the columns for ‘Amanda’ and ‘Maxine’
print("6. Amanda and Maxine temperatures:")
print(temperatures[['Amanda', 'Maxine']])
print()

# 7. Select elements for ‘Amanda’ and ‘Maxine’ in ‘Morning’ and ‘Afternoon’
print("7. Amanda and Maxine (Morning & Afternoon):")
print(temperatures.loc[['Morning', 'Afternoon'], ['Amanda', 'Maxine']])
print()

# 8. Use describe to produce descriptive statistics
print("8. Descriptive statistics:")
print(temperatures.describe())
print()

# 9. Transpose temperatures
print("9. Transposed DataFrame:")
print(temperatures.T)
print()

# 10. Sort temperatures by column names alphabetically
print("10. Columns sorted alphabetically:")
print(temperatures.sort_index(axis=1))